name: "Download Snyk and Initialize"
description: "Download Snyk and Initialize"
inputs:
  snyk-token:
    description: 'Snyk authentication token'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Donwload, Install and Initialize Snyk"
      shell: bash
      run: |
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x ./snyk
        mv ./snyk /usr/local/bin/
        snyk auth $SNYK_TOKEN
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}

